

const Home = () => {

    return (
        <>
            <main className="mt-[98px] bg-black-02 text-white">
                <section id="mecanique">
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Expedita rerum ipsum itaque facilis ea voluptatum et repellat! Nostrum culpa quibusdam eos quia dolor rem nihil reiciendis provident ad vitae veniam eligendi magnam, odit, architecto corporis ex modi impedit expedita quas quod fugiat! Labore nemo rerum perferendis ducimus eveniet, porro odio repellendus molestias amet dolorem alias. Mollitia, voluptates optio incidunt quibusdam quisquam nemo doloremque ut repudiandae veniam aspernatur dignissimos molestias labore aliquam eveniet laboriosam? Suscipit temporibus numquam eligendi assumenda nisi sapiente vel ullam quia quibusdam dolores iure, dignissimos reiciendis cumque necessitatibus dolorem perspiciatis quisquam perferendis labore debitis culpa. Officiis commodi saepe possimus inventore dolorem, quo repudiandae porro quas sit, placeat voluptatibus provident! Molestiae culpa laboriosam eius obcaecati iure suscipit quas aliquam delectus magnam. Obcaecati dicta, ipsum pariatur praesentium incidunt sapiente porro voluptate laboriosam, deserunt delectus quam corporis perferendis fugit rem eaque magni eveniet dolor sunt distinctio! Quasi, sunt quidem ut non mollitia ex velit omnis in, iure eaque architecto magni doloremque? Quae quasi aliquid veritatis aperiam facilis vel similique natus molestias quam suscipit et, at amet voluptatibus voluptate officia fugit assumenda ipsam perspiciatis fuga? Inventore atque sapiente, omnis nam labore, delectus nesciunt pariatur adipisci recusandae consectetur sequi harum laboriosam itaque rem!
                </section>
                <section id="carrosserie">
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Expedita rerum ipsum itaque facilis ea voluptatum et repellat! Nostrum culpa quibusdam eos quia dolor rem nihil reiciendis provident ad vitae veniam eligendi magnam, odit, architecto corporis ex modi impedit expedita quas quod fugiat! Labore nemo rerum perferendis ducimus eveniet, porro odio repellendus molestias amet dolorem alias. Mollitia, voluptates optio incidunt quibusdam quisquam nemo doloremque ut repudiandae veniam aspernatur dignissimos molestias labore aliquam eveniet laboriosam? Suscipit temporibus numquam eligendi assumenda nisi sapiente vel ullam quia quibusdam dolores iure, dignissimos reiciendis cumque necessitatibus dolorem perspiciatis quisquam perferendis labore debitis culpa. Officiis commodi saepe possimus inventore dolorem, quo repudiandae porro quas sit, placeat voluptatibus provident! Molestiae culpa laboriosam eius obcaecati iure suscipit quas aliquam delectus magnam. Obcaecati dicta, ipsum pariatur praesentium incidunt sapiente porro voluptate laboriosam, deserunt delectus quam corporis perferendis fugit rem eaque magni eveniet dolor sunt distinctio! Quasi, sunt quidem ut non mollitia ex velit omnis in, iure eaque architecto magni doloremque? Quae quasi aliquid veritatis aperiam facilis vel similique natus molestias quam suscipit et, at amet voluptatibus voluptate officia fugit assumenda ipsam perspiciatis fuga? Inventore atque sapiente, omnis nam labore, delectus nesciunt pariatur adipisci recusandae consectetur sequi harum laboriosam itaque rem!
                </section>
                <section id="auto">
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Expedita rerum ipsum itaque facilis ea voluptatum et repellat! Nostrum culpa quibusdam eos quia dolor rem nihil reiciendis provident ad vitae veniam eligendi magnam, odit, architecto corporis ex modi impedit expedita quas quod fugiat! Labore nemo rerum perferendis ducimus eveniet, porro odio repellendus molestias amet dolorem alias. Mollitia, voluptates optio incidunt quibusdam quisquam nemo doloremque ut repudiandae veniam aspernatur dignissimos molestias labore aliquam eveniet laboriosam? Suscipit temporibus numquam eligendi assumenda nisi sapiente vel ullam quia quibusdam dolores iure, dignissimos reiciendis cumque necessitatibus dolorem perspiciatis quisquam perferendis labore debitis culpa. Officiis commodi saepe possimus inventore dolorem, quo repudiandae porro quas sit, placeat voluptatibus provident! Molestiae culpa laboriosam eius obcaecati iure suscipit quas aliquam delectus magnam. Obcaecati dicta, ipsum pariatur praesentium incidunt sapiente porro voluptate laboriosam, deserunt delectus quam corporis perferendis fugit rem eaque magni eveniet dolor sunt distinctio! Quasi, sunt quidem ut non mollitia ex velit omnis in, iure eaque architecto magni doloremque? Quae quasi aliquid veritatis aperiam facilis vel similique natus molestias quam suscipit et, at amet voluptatibus voluptate officia fugit assumenda ipsam perspiciatis fuga? Inventore atque sapiente, omnis nam labore, delectus nesciunt pariatur adipisci recusandae consectetur sequi harum laboriosam itaque rem!
                </section>
            </main>
        </>
    );
};

export default Home;
